// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}

//app/page.tsx
import { UserButton } from "@clerk/nextjs";

export default function Home() {
  return (
    <div>
      <UserButton />
    </div>
  )
}

import 'dotenv/config'; // To read CLERK_API_KEY
import clerk from '@clerk/clerk-sdk-node';

const userList = await clerk.users.getUserList();


// Import required modules
const express = require('express');
const { auth, requiresAuth } = require('express-openid-connect'); // add requiresAuth
const request = require('request');
const axios = require('axios');

// Create an Express app
const app = express();

// Add authentication middleware
app.use(
  auth({
    issuerBaseURL: 'https://scenecraftr.us.auth0.com',
    baseURL: 'https://www.scenecraftr.com',
    clientID: 'RlTJfPJfBprVZ1GT0h1JB4pOBXsKwQ7a', // updated clientID
    secret: process.env.AUTH0_CLIENT_SECRET, // use environment variable
    authRequired: false,
    auth0Logout: true,
    routes: {
      login: '/login',
      callback: '/callback',
      logout: '/logout',
      postLogoutRedirect: 'https://www.scenecraftr.com'
    }
  })
);

// Define a route for the home page
app.get('/', (req, res) => {
  res.send('Hello, world!');
});

// Define a route for the user profile page, which requires authentication
app.get('/profile', requiresAuth(), (req, res) => {
  res.send(JSON.stringify(req.oidc.user));
});

// Export the Express app
export default app;
